#!/usr/bin/python3
#+
# Seaskirt example: simple listener for Asterisk Manager events.
#
# Copyright 2007-2022 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0 <https://creativecommons.org/publicdomain/zero/1.0/>;
# do with it what you will.
#-

import sys
import time
import signal
import getopt
import seaskirt

def interrupted(signum, frame) :
    raise KeyboardInterrupt("somebody killed me")
#end interrupted

poll_delay = 0.25 # to ensure output gets periodically flushed
opts, args = getopt.getopt \
  (
    sys.argv[1:],
    "",
    ["debug", "user=", "password=", "want="]
  )
user = None
password = None
debug = False
events_wanted = None
for keyword, value in opts :
    if keyword == "--debug" :
        debug = True
    elif keyword == "--password" :
        password = value
    elif keyword == "--user" :
        user = value
    elif keyword == "--want" :
        if events_wanted == None :
            events_wanted = set()
        #end if
        events_wanted.add(value.lower())
    #end if
#end for
if user == None or password == None :
    raise getopt.GetoptError("--user and --password are required")
#end if

signal.signal(signal.SIGTERM, interrupted)

the_conn = seaskirt.Manager \
  (
    username = user,
    password = password,
    want_events = True,
    debug = debug
  )
if debug :
    sys.stdout.write("the_conn opened, hello = \"%s\"\n" % the_conn.hello)
#end if

try :
    while True :
        response = the_conn.get_response(poll_delay)
        if response != None :
            if events_wanted == None or response["Event"].lower() in events_wanted :
                sys.stdout.write \
                  (
                        "%s: Event: \"%s\", contents {%s}\n"
                    %
                        (
                                "%04d-%02d-%02d %02d:%02d:%02dZ"
                            %
                                time.gmtime()[:6],
                            response["Event"],
                            ", ".join
                              (
                                "%s : %s" % (repr(key), repr(response[key]))
                                for key in sorted(response.keys())
                              )
                        )
                  )
            #end if
        else :
            # sys.stderr.write("No events yet\n") # debug
            sys.stderr.flush() # so I can log to file without losing events
        #end if
    #end while
except KeyboardInterrupt :
    pass # exit loop
#end try

the_conn.close()
