#!/usr/bin/python3
#+
# Seaskirt example: using my Asterisk Manager library to place a call,
# using the “Originate” action.
#
# Every call has two ends. In asterisk, each end is called a “channel”.
# Channels can be created from contexts in the dialplan, by using a
# channel specifier of the form “Local/«extension»@«context»”. Or you
# can connect to a channel driver with a channel specifier of the form
# “«prefix»/«endpoint»”, where “«prefix»” could for example be “PJSIP”
# for SIP calls, or “DAHDI” for analog/ISDN calls.
#
# With the AMI “Originate” action, you define one end of the call
# with a channel specification, while the other end is given as the
# name of a context in the dialplan, and an extension to dial in that
# context.
#
# Example uses:
#
# Ringing a SIP phone and passing it a call to another number:
#     dial --channel="PJSIP/«endpoint»" --context="«outbound-context»" «number»
#
# Calling a number and connecting it to an internal channel:
#     dial --channel="Local/s@«inbound-context»" --context="«outbound-context»" «number»
#
# Copyright 2007-2022 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import asyncio
import getopt
import seaskirt

opts, args = getopt.getopt \
  (
    sys.argv[1:],
    "",
    ["async", "channel=", "context=", "debug", "password=", "ssl-ca=", "timeout=", "user="]
  )
channel = None
context = None
timeout = 10 # default
user = None
password = None
ssl_ca = None
debug = False
call_async = False
for keyword, value in opts :
    if keyword == "--async" :
        call_async = True
    elif keyword == "--channel" :
        channel = value
    elif keyword == "--context" :
        context = value
    elif keyword == "--debug" :
        debug = True
    elif keyword == "--password" :
        password = value
    elif keyword == "--ssl-ca" :
        ssl_ca = value
    elif keyword == "--timeout" :
        timeout = float(value)
    elif keyword == "--user" :
        user = value
    #end if
#end for
if len(args) != 1 :
    raise getopt.GetoptError("expecting one arg, the extension to dial")
#end if
if context == None or channel == None :
    raise getopt.GetoptError("--channel and --context are required")
#end if
if user == None or password == None :
    raise getopt.GetoptError("--user and --password are required")
#end if
extension = args[0]

async def main() :
    the_conn = await seaskirt.ManagerAsync \
      (
        username = user,
        password = password,
        ssl_context = ssl_ca,
        want_events = call_async,
        id_gen = seaskirt.naturals()
      )
    the_conn.debug = debug
    sys.stdout.write("the_conn opened, hello = \"%s\"\n" % the_conn.hello)
    originate_args = \
        {
            "action" : "Originate",
            "parms" :
                {
                    "Channel" : channel,
                    "Context" : context,
                    "Exten" : extension,
                    "Priority" : 1,
                    "Async" : ("false", "true")[call_async],
                    "Timeout" : round(timeout * 1000),
                },
        }
    if call_async :
        await the_conn.send_request(**originate_args)
        # the OriginateResponse event is only returned on this
        # connection, not to any other listener. Unfortunately,
        # to actually received the event, I have to enable
        # receipt of all other events.
        while True :
            event = await the_conn.get_response()
            sys.stdout.write("async response %s\n" % repr(event))
            if event.get("Event") == "OriginateResponse" :
                break
        #end while
    else :
        response = await the_conn.transact(**originate_args)
        sys.stdout.write(repr(response) + "\n")
    #end if
    await the_conn.transact("Logoff", {})
    await the_conn.close()
#end main

asyncio.run(main())
