#!/usr/bin/python
#+
# Simple listener for Asterisk events.
#
# Created by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-

import sys
import time
import select
import Asterisk

TheConn = Asterisk.Manager()
sys.stdout.write("TheConn opened, hello = \"%s\"\n" % TheConn.Hello)
TheConn.Authenticate("user", "secret", True)

try :
	while True :
		(ReadReady, _, _) = \
			select.select((TheConn,), (), (), 1.0)
		if TheConn in ReadReady :
			Response = TheConn.GetResponse()
			sys.stdout.write \
			  (
					"%s: Event: \"%s\", contents %s\n"
				%
					(
							"%04d-%02d-%02d %02d:%02d:%02dZ"
						%
							time.gmtime()[:6],
						Response["Event"],
						repr(Response),
					)
			  )
		else :
			pass # sys.stderr.write("No events yet\n") # debug
		#end if
	#end while
except KeyboardInterrupt :
	pass # exit loop
#end try

TheConn.close()
