#!/usr/bin/python3
#+
# Seaskirt example: simple listener for output from the Asterisk console.
# Note that the console socket is not normally accessible by nonprivileged
# users, so this script should be run as root.
#
# Copyright 2022 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0 <https://creativecommons.org/publicdomain/zero/1.0/>;
# do with it what you will.
#-

import sys
import asyncio
import seaskirt

poll_delay = 0.25 # to ensure output gets periodically flushed

async def main() :
    console = await seaskirt.ConsoleAsync()
    while True :
        verbosity, response = await console.get_response()
        if response != None :
            sys.stdout.write("[%d] %s" % (verbosity, response))
        else :
            sys.stdout.flush()
        #end if
    #end while
#end main

asyncio.run(main())
