#!/usr/bin/python3
#+
# Simple script using my Asterisk Manager library to place a call.
#
# Created 2007 July 20 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
# Add timeout option 2008 July 31.
# Add --user and --password, no more default channel or context 2008 August 14.
#-

import sys
import getopt
import Asterisk

opts, args = getopt.getopt \
  (
    sys.argv[1:],
    "",
    ["channel=", "context=", "timeout=", "user=", "password="]
  )
channel = None
context = None
timeout = 10 # default
user = None
password = None
for keyword, value in opts :
    if keyword == "--channel" :
        channel = value
    elif keyword == "--context" :
        context = value
    elif keyword == "--password" :
        password = value
    elif keyword == "--timeout" :
        timeout = float(value)
    elif keyword == "--user" :
        user = value
    #end if
#end for
if len(args) != 1 :
    raise getopt.GetoptError("expecting one arg, the extension to dial")
#end if
if context == None or channel == None :
    raise getopt.GetoptError("--channel and --context are required")
#end if
if user == None or password == None :
    raise getopt.GetoptError("--user and --password are required")
#end if
extension = args[0]

the_conn = Asterisk.Manager()
sys.stdout.write("the_conn opened, hello = \"%s\"\n" % the_conn.hello)
the_conn.authenticate(user, password)

response = the_conn.transact \
  (
    action = "Originate",
    parms =
        {
            "Channel" : channel,
            "Context" : context,
            "Exten" : extension,
            "Priority" : 1,
            "Timeout" : int(round(timeout * 1000)),
        }
  )
sys.stdout.write(repr(response) + "\n")
the_conn.transact("Logoff", {})
the_conn.close()
