#!/usr/bin/python3
#+
# Simple script using my Asterisk Manager library to place a call.
# Example uses:
#
#     dial --channel="PJSIP/«endpoint»" --context="«outbound-context»" «number»
#     dial --channel="Local/s@«inbound-context»" --context="«outbound-context»" «number»
#
# Copyright 2007-2022 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import getopt
import seaskirt

opts, args = getopt.getopt \
  (
    sys.argv[1:],
    "",
    ["async", "channel=", "context=", "debug", "timeout=", "user=", "password="]
  )
channel = None
context = None
timeout = 10 # default
user = None
password = None
debug = False
call_async = False
for keyword, value in opts :
    if keyword == "--async" :
        call_async = True
    elif keyword == "--channel" :
        channel = value
    elif keyword == "--context" :
        context = value
    elif keyword == "--debug" :
        debug = True
    elif keyword == "--password" :
        password = value
    elif keyword == "--timeout" :
        timeout = float(value)
    elif keyword == "--user" :
        user = value
    #end if
#end for
if len(args) != 1 :
    raise getopt.GetoptError("expecting one arg, the extension to dial")
#end if
if context == None or channel == None :
    raise getopt.GetoptError("--channel and --context are required")
#end if
if user == None or password == None :
    raise getopt.GetoptError("--user and --password are required")
#end if
extension = args[0]

the_conn = seaskirt.Manager()
the_conn.debug = debug
sys.stdout.write("the_conn opened, hello = \"%s\"\n" % the_conn.hello)
the_conn.authenticate(user, password)

response = the_conn.transact \
  (
    action = "Originate",
    parms =
        {
            "Channel" : channel,
            "Context" : context,
            "Exten" : extension,
            "Priority" : 1,
            "Async" : ("false", "true")[call_async],
            "Timeout" : round(timeout * 1000),
        }
  )
sys.stdout.write(repr(response) + "\n")
the_conn.transact("Logoff", {})
the_conn.close()
