#!/usr/bin/python
#+
# Simple script using my Asterisk Manager library to place a call.
#
# Created 2007 July 20 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
# Add timeout option 2008 July 31.
#-

import sys
import getopt
import Asterisk

(Opts, Args) = getopt.getopt \
  (
	sys.argv[1:],
	"",
	["channel=", "context=", "timeout="]
  )
if len(Args) != 1 :
	raise getopt.GetoptError("expecting one arg, the extension to dial")
#end if
Extension = Args[0]
Channel = "IAX2/Testing" # default
Context = "directout" # default
Timeout = 10 # default
for Keyword, Value in Opts :
	if Keyword == "--channel" :
		Channel = Value
	elif Keyword == "--context" :
		Context = Value
	elif Keyword == "--timeout" :
		Timeout = float(Value)
	#end if
#end for

TheConn = Asterisk.Manager()
sys.stdout.write("TheConn opened, hello = \"%s\"\n" % TheConn.Hello)
TheConn.Authenticate("user", "secret")

Response = TheConn.Transact \
  (
	Action = "Originate",
	Parms =
		{
			"Channel" : Channel,
			"Context" : Context,
			"Exten" : Extension,
			"Priority" : 1,
			"Timeout" : int(Timeout * 1000),
		}
  )
sys.stdout.write(repr(Response) + "\n")
TheConn.Transact("Logoff", {})
TheConn.close()
