#!/usr/bin/python
#+
# Simple script using my Asterisk Manager library to perform arbitrary functions.
#
# Created 2008 August 14 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
# Remove --multi (now automatic) 2008 August 15.
# Add --debug and variables 2008 August 15.
# Add special QueueStatus handling 2008 August 22.
#-

import sys
import getopt
import Asterisk

opts, args = getopt.getopt \
  (
    sys.argv[1:],
    "",
    ["debug", "user=", "password="]
  )
user = None
password = None
debug = False
for keyword, value in opts :
    if keyword == "--debug" :
        debug = True
    elif keyword == "--password" :
        password = value
    elif keyword == "--user" :
        user = value
    #end if
#end for
if user == None or password == None :
    raise getopt.GetoptError("--user and --password are required")
#end if
if len(args) == 0 :
    raise getopt.GetoptError("need at least one arg, the action to perform")
#end if
parms = {}
vars = None
action = args[0]
for arg in args[1:] :
    keyword, value = arg.split("=", 1)
    if keyword.lower() == "variable" :
        if vars == None :
            vars = {}
        #end if
        varname, value = value.split("=", 1)
        vars[varname] = value
    else :
        parms[keyword] = value
    #end if
#end for

the_conn = Asterisk.Manager()
if debug :
    the_conn.debug = True
#end if
sys.stdout.write("the_conn opened, hello = \"%s\"\n" % the_conn.hello)
the_conn.authenticate(user, password)

if action.lower() == "queuestatus" and len(parms) == 0 and vars == None :
    response = the_conn.get_queue_status()
else :
    response = the_conn.transact(action, parms, vars)
#end if
sys.stdout.write(repr(response) + "\n")
the_conn.transact("Logoff", {})
the_conn.close()
